spring:
  datasource:
    url: jdbc:mysql://39.106.97.184:3306/testby?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    driverClassName: com.mysql.jdbc.Driver
    username: root
    password: 123456
mybatis:
  mapper-locations: classpath:/mapper/*Mapper.xml
  type-aliases-package: com.example.xiangdabing.entity
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

